on:
  issue_comment:
    types: [created]
name: Merge
jobs:
  merge:
    name: Merge
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/pull-translations')
    runs-on: ubuntu-latest
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.ref }}
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: yarn add babel-core@^7.0.0-bridge.0 @babel/core --frozen-lockfile
      - name: Merge with master
        run: |
          git config --global user.email "dev@pleo.io"
          git config --global user.name "Dev bot"
          git fetch && git merge origin/master --allow-unrelated-histories

      - name: Remove messages
        if: failure()
        run: echo -n "" > src/locales/en/messages.po
      - name: Extracting messages
        if: failure()
        run: npx lingui extract
      - name: Commiting messages
        if: failure()
        env:
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git add .
          git commit -m "Merge with master: message extraction"
          git push https://igorDolzh:$PUSH_TOKEN@github.com/${{ github.repository }} HEAD:${{ steps.comment-branch.outputs.ref }}
    #   - name: Push changes
    #     if: failure()
    #     uses: ad-m/github-push-action@master
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       branch: ${{ steps.comment-branch.outputs.ref }}
