name: Run yarn extract-messages

on: push

jobs:
  fix_errors:
    name: Commiting
    if: contains(github.event.commits[0].message, '-translate-')
    env:
      CI: "true"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: yarn add babel-core@^7.0.0-bridge.0 @babel/core --frozen-lockfile
      - uses: navikt/github-app-token-generator@v1
        id: gettoken
        with:
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          app-id: ${{ secrets.APP_ID }}
      - name: Extracting messages
        run: yarn extract-messages
      - name: Push changes
        env:
          APP_INSTALLATION_TOKEN: ${{ steps.get-token.outputs.token }}
        run: |
          git config --global user.email "igor.techweb@gmail.com"
          git config --global user.name "Igor Dolzhenkov"
          git add .
          git commit -m "Messages updated"
          git push https://igorDolzh:$APP_INSTALLATION_TOKEN@github.com/${{ github.repository }} HEAD:"${GITHUB_REF:11}"
    #   - name: Push changes 2
    #     with:
    #       script: |
    #         const githubI = await new Octokit({
    #             auth: steps.gettoken.outputs.token
    #         })
    #         await githubI.git.updateRef({
    #           owner: 'pleo-io',
    #           repo: github.repository,
    #           ref: 'heads/chore/ch44690/the-process-when-translations-are-not-required',
    #           sha: '1f47b3d',
    #           force: false
    #         })
