name: Run yarn extract-messages

on: push

jobs:
  fix_errors:
    name: Commiting
    if: contains(github.event.commits[0].message, '-translate-')
    env:
      CI: "true"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: yarn add babel-core@^7.0.0-bridge.0 @babel/core --frozen-lockfile
      - uses: navikt/github-app-token-generator@v1
        id: gettoken
        with:
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          app-id: ${{ secrets.APP_ID }}
      - name: Extracting messages2
        run: npx lingui extract
      - name: Push changes
        env:
          APP_INSTALLATION_TOKEN: ${{ steps.gettoken.outputs.token }}
        id: commit
        run: |
          git config --global user.email "igor.techweb@gmail.com"
          git config --global user.name "Igor Dolzhenkov"
          git add .
          git commit -m "Messages updated"
      #   - name: Run forestx
      #     run: ${{ steps.commit.outputs }}
      #   git push https://igorDolzh:$APP_INSTALLATION_TOKEN@github.com/${{ github.repository }} HEAD:"${GITHUB_REF:11}"
      - uses: actions/github-script@v3
        with:
          github-token: ${{steps.gettoken.outputs.token}}
          script: |
            await github.git.updateRef({
                owner: 'igorDolzh',
                repo: 'lingui-test',
                ref: 'heads/igor-push-messages',
                sha: '06c758adffa0fc91da4d30b9ef4740209b1b30f7',
                force: true
            })
