on:
  issue_comment:
    types: [created]
name: Push translations
jobs:
  merge:
    name: Push translations
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/push-messages')
    runs-on: ubuntu-latest
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.ref }}
      - name: Lokalise File Push
        uses: igorDolzh/lokalise-file-push@0.0.8
        with:
          # Api token for the Lokalise account
          # with read/write access to the project
          api-token: ${{ secrets.LOCALIZE_TOKEN }}

          # ID of the project to sync
          project-id: ${{ secrets.LOCALIZE_PROJECT }}

          # The relative file path where language files will be found
          file-path: src/locales/en/messages.po

          tag: pre-release
