on:
  pull_request:
    types: [closed]
name: Pull request
jobs:
  rebase:
    name: Pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
